[package]
name = "dalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
leptos = "0.3.1"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
